/**
 * What the arc generator adds on top of the shared Fabula shape.
 *
 * The shape itself — `FabulaEventSchema`, `FabulaArcSchema`, `FABULA_BLOCK`, `eventsInOrder`,
 * `exitStateFor` — moved to [`src/schema/fabula.ts`](../schema/fabula.ts) under
 * [ADR 0019](../../docs/adr/0019-fabula-only-packages.md), and the projection that lets a
 * Fabula-only artifact be linted at all moved to
 * [`src/authoring/lint-fabula.ts`](../authoring/lint-fabula.ts). This file keeps the two things
 * that are genuinely the *generator's*: the deliverable envelope, and the stricter parse a
 * generator is held to.
 *
 * **Why generation is held to a stricter shape than the shared schema requires.** ADR 0019 makes
 * `pov` and `dramatic_function` optional at the Fabula layer, because extraction structurally
 * cannot fill them before scene boundaries exist. That argument does not apply here: a generator
 * invents Fabula and Syuzhet in one act, so it always knows whose scene this is and what it is
 * for, and a generated arc that omits them has failed to answer the prompt rather than hit a
 * layer boundary. `GeneratedFabulaArcSchema` keeps that guarantee local to the generator instead
 * of pushing it back onto the shared contract, where it would break extraction.
 */

import { z } from 'zod';

import {
  FABULA_BLOCK,
  FabulaEventSchema,
  eventsInOrder,
  type FabulaArc,
  type FabulaEvent,
} from '../schema/fabula';
import { WorldModelSeedSchema } from '../schema/story-package';
import type { ArcBrief } from './brief';

/** The Fabula event a *generator* must produce: the shared shape with its Syuzhet fields required. */
export const GeneratedFabulaEventSchema = FabulaEventSchema.extend({
  pov: z.string().min(1),
  dramatic_function: z.string().min(1),
  location_id: z.string().min(1),
});

export const GeneratedFabulaArcSchema = z.object({
  title: z.string().min(1),
  world_model_seed: WorldModelSeedSchema,
  events: z.array(GeneratedFabulaEventSchema).min(1),
});

export interface FabulaBlock {
  readonly generator: string;
  /** The model that produced the arc. A result that does not say this is not a measurement. */
  readonly model: string;
  readonly generated_at: string;
  readonly brief: ArcBrief;
  readonly events: FabulaEvent[];
  /** Atomic repairs applied after the first pass, in order. Empty when the arc linted clean. */
  readonly repairs: string[];
}

/**
 * The deliverable: `world_model_seed` populated, `scene_cards` empty, event list carried alongside.
 *
 * `DraftStoryPackageSchema` is a `looseObject` exactly so a package can hold blocks the schema has
 * never heard of — both long fixtures carry `_authoring_conventions` the same way, and
 * `src/authoring/transfer.ts` reports them as `extra_blocks` rather than dropping them. That is
 * the seam the event list uses, so `src/segmentation` can take this object straight from either
 * entry point without a second file format existing.
 */
export function draftPackage(
  arc: FabulaArc,
  storyId: string,
  block: Omit<FabulaBlock, 'events'>,
): Record<string, unknown> {
  return {
    schema_version: '1.0',
    package_version: 1,
    story_id: storyId,
    world_model_seed: arc.world_model_seed,
    scene_cards: [],
    voice_card: {},
    metadata: {
      title: arc.title,
      source: `original arc generated by ${block.generator} (${block.model})`,
      created_at: block.generated_at,
    },
    [FABULA_BLOCK]: { ...block, events: eventsInOrder(arc) },
  };
}
